remix-run/react-router-website

app/components/doc-route.tsx, app/modules/gh-docs/index.ts, app/root.tsx, app/routes/$.tsx, app/routes/$lang.$ref.tsx, app/routes/$lang.$ref/index.tsx, app/routes/index.tsx
See https://github.com/remix-run/remix/releases/tag/remix@1.6.5
---
Just like https://github.com/remix-run/remix/pull/4684 & https://github.com/remix-run/examples/pull/82
=> fix: fix `useLoaderData` usage

app/routes/$lang.$ref/index.tsx
Related to https://github.com/remix-run/react-router-website/pull/25
=> fix: stat `count` can be `null`

app/modules/stats/index.tsx
we got the below error when back to the home page
the root cause is that the `npmDownloads` is `NaN`
the npm download counts API response
```
query [
{
downloads: 1993005,
start: '2015-01-10',
end: '2016-01-10',
package: 'react-router'
},
{
downloads: 9876499,
start: '2016-01-11',
end: '2017-01-11',
package: 'react-router'
},
{
downloads: 28481372,
start: '2017-01-12',
end: '2018-01-12',
package: 'react-router'
},
{
downloads: 62270439,
start: '2018-01-13',
end: '2019-01-13',
package: 'react-router'
},
{
downloads: 127107479,
start: '2019-01-14',
end: '2020-01-14',
package: 'react-router'
},
{
downloads: 184417302,
start: '2020-01-15',
end: '2021-01-15',
package: 'react-router'
},
{
downloads: 250765671,
start: '2021-01-16',
end: '2022-01-16',
package: 'react-router'
},
{
downloads: …
```
=> fix: npm downloads count

app/routes/brand.tsx
- revised the spelling of `Guidlines` to `Guidelines` in the brand page metadata
- ran cSpell against the entire repo to check for other misspellings and didn't find any :)
=> fix(routes/brand): fix typo

README.md
This PR fixes the setup description in README.md.
Currently, README.md says "Copy the .env" file but while setting up the project we do not have a .env file. Instead, we create .env file and copy the contents of .env.example to it.
=> fix: readme setup description

.github/workflows/deploy.yml, .github/workflows/format.yml, .github/workflows/lint.yml
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
- https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency
- > The fully-formed ref of the branch or tag that triggered the workflow run. For workflows triggered by `push`, this is the branch or tag ref that was pushed. For workflows triggered by `pull_request`, this is the pull request merge branch. For workflows triggered by `release`, this is the release tag created. For other triggers, this is the branch or tag ref that triggered the workflow run. This is only set if a branch or tag is available for the event type. The ref given is fully-formed, meaning that for branches the format is `refs/heads/<branch_name>`, for pull requests it is …
=> chore: remove `styfle/cancel-workflow-action` usage

app/styles.source.css
Changed the "display" property of the "code" element to "grid" to fix an issue where the green code highlighter ("span" element) did not highlight the entire line of code on mobile or smaller screen devices. The issue was caused by the parent "code" element being inline and not filling up the entire width of its parent "pre" element.
Screenshots of the issue before and after the changes are included for better visualization.
Before:
After:
This change only affects the "code" element and does not impact any other CSS rules or elements.
=> Update code element's display property

app/styles.source.css
This pull request resolves the issue of the `code` element not assuming the full width of its parent element (`pre`), thereby causing the highlighting `span` elements (children of the `code` element) not to span the entire length of the code they are highlighting.
The issue occurred because the `code` element is an inline property, which means it flows with surrounding text. However, by setting the display property to inline-block, we can change the display behavior of the element to behave like a block-level element, allowing us to set the width and height properties.
To ensure that the code element assumes the width of its parent container, we explicitly set the min-width property to 100%. This allows the `code` element to expand to the full available width of its parent element …
=> fix: code elements should at least be full parent width

app/components/doc-route.tsx
This PR addresses the side navigation bar links on the documentation page (Issue #83 ). The links were working on firefox and safari, but not on chrome, edge and chrome mobile devices. 
I used react router's `<Link>` tag instead of the  HTML `<a>` tag to fix this.
Subsequent links now scroll to the desired anchor on the first click. 
Tested on Safari, Chrome and Brave. (MacOS) and Chrome on Android.
=> fix(#83): side nav links

app/components/doc-route.tsx, app/modules/gh-docs/docs.ts, app/routes/$lang.$ref.$.tsx, app/routes/brand.tsx
=> feat: Add changelog rendering

app/styles/tailwind.css
Same contribution as we received in [remix-website](https://github.com/remix-run/remix-website/pull/241)
Makes scrollbars and other defaults look a lot better in dark mode
=> Add color-scheme:dark when the dark class is applied

app/routes/$lang.$ref.$.tsx, app/routes/$lang.$ref._index.tsx, app/routes/$lang.$ref.tsx
I managed to fix the element overlapping issue (#106), but because I needed to change some elements from block to flex it required some other changes like removing all the `ml-72`s and adjusting the padding. The Remix website source helped a lot on how to do this, and most of these changes come directly from there.
The footer is also slightly different due to the change from block to flex, so no problem if this is not merged because of that. Closest I could get it to working with flex instead of block :)
=> Fix overlapping issue

app/modules/docsearch.tsx, app/routes/$lang.$ref.$.tsx, app/routes/$lang.$ref.tsx, app/styles/docsearch.css, app/ui/utils.ts, package-lock.json, package.json, vite.config.ts
I'm still very interested in Orama (see #104), however we have no excuse for not having search on [reactrouter.com](https://reactrouter.com/)
Going ahead and adding DocSearch since
1. it's free
2. it's used on [remix.run](https://remix.run/) and so easy to implement
Closes #75
=> Add DocSearch by Algolia

app/styles/docs.css
...unlike normal links in dark mode, or both types of links in light mode.
| Inline code link, before (hover & active) | Inline code link, after (hover & active) |
|-|-|
| ![20240602T052818+0900](https://github.com/remix-run/react-router-website/assets/11722318/69f9cbf5-c244-4e91-9c56-a6314b748258) | ![20240602T052748+0900](https://github.com/remix-run/react-router-website/assets/11722318/2b5f3b0b-5a71-44ca-82eb-8c36818fd767) |
| Normal link (hover & active) | Inline code link, light mode (hover & active) |
|-|-|
| ![20240602T052843+0900](https://github.com/remix-run/react-router-website/assets/11722318/5a63b153-7428-445a-a9fc-93804bbcf3e7) | ![20240602T053409+0900](https://github.com/remix-run/react-router-website/assets/11722318/3fc155e5-8670-4009-adf6-05a4fea6579f) |
(Test page: …
=> fix: pre/code links don't change color when :active in dark mode

app/components/docs-menu/data.server.ts, app/pages/api-layout.tsx
Trying to root out perf issues with the api routes. The following is based on averages of 10 trials
**Setup**
- run `NO_CACHE=1 npm run dev`
- Disable Cache in chrome dev tools
- Go to http://localhost:3000/dev/api/react-router
**Results**
| Loader           | Before (ms) | After (ms) |
| ---------------- | ----------- | ---------- |
| `api-layout.tsx` | 735.80      | 380.338    |
=> api docs perf improvement

app/pages/api-layout.tsx, app/pages/guides-layout.tsx
Adding `shouldRevalidate` with `defaultShouldRevalidate` returned from the layout routes, which avoids needless and expensive reconstruction of the API menu 
https://github.com/user-attachments/assets/f9ce6eca-8ef5-4b5c-8f6c-df18155bf405
=> Add `shouldRevalidate` to api and guides layout

app/modules/stats/index.tsx, app/pages/splash.tsx
=> defer stats in loader

app/components/docs-header/docs-header.tsx, app/pages/splash.tsx
as the title says, tiny pr that fixes the alt text for two instances of the react router logo on the website. changes it from nine to six dots
=> correct alt text of react router logo from nine dots to six

app/ui/utils.ts
I noticed a bug where the code blocks click-to-copy buttons aren't available on the initial page load or after a page refresh.
The buttons became available again after the next navigation event.
https://github.com/user-attachments/assets/2194b18d-a597-48ab-94ca-ec8e5cdf4230
I couldn't figure out the exact cause of the issue, but I suspect that it has to do with hydration. The markup is overridden after the effect responsible for creating the buttons runs.
In my investigation, I referred to the code for the Remix documentation website ([here](https://github.com/remix-run/remix-website/blob/main/app/routes/docs.%24lang.%24ref.tsx#L916)), which shares a similar implementation, but I am unsure why it's not an issue there.
Because I couldn't pinpoint the exact problem, I decided to remove the …
=> fix: ensure click-to-copy buttons are created after hydration

app/components/docs-menu/menu.tsx
=> Add link to changelog

LICENSE.md, app/pages/splash.tsx
This PR makes the following changes:
1. Adds a link to shopify.com around the Shopify logo in the splash page footer
2. Updates the copyright year to 2025 in the splash page footer
3. Updates the copyright year to 2025 in LICENSE.md
These changes are good for SEO attribution and maintain accurate copyright information across the project.
I've followed the contributor guidelines by:
- Forking and cloning the repo
- Creating a branch for these changes
- Pushing the changes to my branch
- Opening this PR in the main repository
Ran locally:
https://screenshot.click/15-14-x8s2l-epnh5.mp4
=> Add Shopify.com link and update copyright year to 2025
